### PR TITLE
Team 5 (Lab02): Update velodyneDriver.cpp for LiDAR raw data resolve

### PR DESCRIPTION
**Pull request by chenweig**
Lab02 Homework Commit

### CODE REVIEW

**Comment by Durant35** [comment]
Pay attension to https://github.com/CPSinSYSU/SHCD2017/issues/9

**Comment by chenweig** [comment]
Team 5 (Lab02): Update velodyneDriver.cpp for LiDAR raw data resolve

**Comment by Goshin** [comment]
Seems you wrongly add a submodule rather than your source code. It will not work without additional amendments.

**Comment by Durant35** [comment]
Some basic information about your works is required. Refer to [#9](https://github.com/CPSinSYSU/SHCD2017/issues/9).

**Pull request closed without merging**
