### PR TITLE
Team 8 (Lab02): Update velodyneDriver.cpp for LiDAR raw data resolve

### PR DESCRIPTION
**Pull request by 14353160lzx**
我们已经修改好了驱动的数据解释

### CODE REVIEW

**Comment by Goshin** [comment]
Some basic information about your works is required. Refer to [#9](https://github.com/CPSinSYSU/SHCD2017/issues/9).

**Comment by Durant35** [comment]
@14353160lzx WTF..... No one in your group pay attention to this pull request? Please follow the requirement, we will not merge until you do that

**Comment by 14353160lzx** [comment]
I'm sorry for that. We have updated the subject of out pull request.
By the way, shall we change our group wiki's members' name to Chinese either?

**Comment by Durant35** [comment]
It will be very nice if you do that. Thank you!

**Pull request merged**
